#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Airlines")]
	public partial class airlinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmindb(admindb instance);
    partial void Updateadmindb(admindb instance);
    partial void Deleteadmindb(admindb instance);
    partial void Insertemployeedb(employeedb instance);
    partial void Updateemployeedb(employeedb instance);
    partial void Deleteemployeedb(employeedb instance);
    partial void Insertflightdb(flightdb instance);
    partial void Updateflightdb(flightdb instance);
    partial void Deleteflightdb(flightdb instance);
    partial void Insertreservationdb(reservationdb instance);
    partial void Updatereservationdb(reservationdb instance);
    partial void Deletereservationdb(reservationdb instance);
    partial void Insertroutesdb(routesdb instance);
    partial void Updateroutesdb(routesdb instance);
    partial void Deleteroutesdb(routesdb instance);
    #endregion
		
		public airlinqDataContext() : 
				base(global::Airline_Reservation.Properties.Settings.Default.AirlinesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public airlinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airlinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airlinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airlinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admindb> admindbs
		{
			get
			{
				return this.GetTable<admindb>();
			}
		}
		
		public System.Data.Linq.Table<employeedb> employeedbs
		{
			get
			{
				return this.GetTable<employeedb>();
			}
		}
		
		public System.Data.Linq.Table<flightdb> flightdbs
		{
			get
			{
				return this.GetTable<flightdb>();
			}
		}
		
		public System.Data.Linq.Table<reservationdb> reservationdbs
		{
			get
			{
				return this.GetTable<reservationdb>();
			}
		}
		
		public System.Data.Linq.Table<routesdb> routesdbs
		{
			get
			{
				return this.GetTable<routesdb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admindb")]
	public partial class admindb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _mobile;
		
		private string _nic;
		
		private string _pass;
		
		private string _cpass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnnicChanging(string value);
    partial void OnnicChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OncpassChanging(string value);
    partial void OncpassChanged();
    #endregion
		
		public admindb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(50)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nic", DbType="NVarChar(50)")]
		public string nic
		{
			get
			{
				return this._nic;
			}
			set
			{
				if ((this._nic != value))
				{
					this.OnnicChanging(value);
					this.SendPropertyChanging();
					this._nic = value;
					this.SendPropertyChanged("nic");
					this.OnnicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="NVarChar(50)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpass", DbType="NVarChar(50)")]
		public string cpass
		{
			get
			{
				return this._cpass;
			}
			set
			{
				if ((this._cpass != value))
				{
					this.OncpassChanging(value);
					this.SendPropertyChanging();
					this._cpass = value;
					this.SendPropertyChanged("cpass");
					this.OncpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employeedb")]
	public partial class employeedb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _first;
		
		private string _last;
		
		private string _gender;
		
		private string _nationality;
		
		private System.Nullable<System.DateTime> _joining;
		
		private string _mobile;
		
		private string _address;
		
		private string _email;
		
		private string _department;
		
		private string _position;
		
		private string _field;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfirstChanging(string value);
    partial void OnfirstChanged();
    partial void OnlastChanging(string value);
    partial void OnlastChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnnationalityChanging(string value);
    partial void OnnationalityChanged();
    partial void OnjoiningChanging(System.Nullable<System.DateTime> value);
    partial void OnjoiningChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnfieldChanging(string value);
    partial void OnfieldChanged();
    #endregion
		
		public employeedb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first", DbType="NVarChar(50)")]
		public string first
		{
			get
			{
				return this._first;
			}
			set
			{
				if ((this._first != value))
				{
					this.OnfirstChanging(value);
					this.SendPropertyChanging();
					this._first = value;
					this.SendPropertyChanged("first");
					this.OnfirstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last", DbType="NVarChar(50)")]
		public string last
		{
			get
			{
				return this._last;
			}
			set
			{
				if ((this._last != value))
				{
					this.OnlastChanging(value);
					this.SendPropertyChanging();
					this._last = value;
					this.SendPropertyChanged("last");
					this.OnlastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality", DbType="NVarChar(50)")]
		public string nationality
		{
			get
			{
				return this._nationality;
			}
			set
			{
				if ((this._nationality != value))
				{
					this.OnnationalityChanging(value);
					this.SendPropertyChanging();
					this._nationality = value;
					this.SendPropertyChanged("nationality");
					this.OnnationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joining", DbType="DateTime")]
		public System.Nullable<System.DateTime> joining
		{
			get
			{
				return this._joining;
			}
			set
			{
				if ((this._joining != value))
				{
					this.OnjoiningChanging(value);
					this.SendPropertyChanging();
					this._joining = value;
					this.SendPropertyChanged("joining");
					this.OnjoiningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(50)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(50)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="NVarChar(50)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="NVarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_field", DbType="NVarChar(50)")]
		public string field
		{
			get
			{
				return this._field;
			}
			set
			{
				if ((this._field != value))
				{
					this.OnfieldChanging(value);
					this.SendPropertyChanging();
					this._field = value;
					this.SendPropertyChanged("field");
					this.OnfieldChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flightdb")]
	public partial class flightdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _type;
		
		private string _model;
		
		private string _seats;
		
		private string _cabins;
		
		private string _takoff;
		
		private string _landing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnseatsChanging(string value);
    partial void OnseatsChanged();
    partial void OncabinsChanging(string value);
    partial void OncabinsChanged();
    partial void OntakoffChanging(string value);
    partial void OntakoffChanged();
    partial void OnlandingChanging(string value);
    partial void OnlandingChanged();
    #endregion
		
		public flightdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NVarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seats", DbType="NVarChar(50)")]
		public string seats
		{
			get
			{
				return this._seats;
			}
			set
			{
				if ((this._seats != value))
				{
					this.OnseatsChanging(value);
					this.SendPropertyChanging();
					this._seats = value;
					this.SendPropertyChanged("seats");
					this.OnseatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cabins", DbType="NVarChar(50)")]
		public string cabins
		{
			get
			{
				return this._cabins;
			}
			set
			{
				if ((this._cabins != value))
				{
					this.OncabinsChanging(value);
					this.SendPropertyChanging();
					this._cabins = value;
					this.SendPropertyChanged("cabins");
					this.OncabinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_takoff", DbType="NVarChar(50)")]
		public string takoff
		{
			get
			{
				return this._takoff;
			}
			set
			{
				if ((this._takoff != value))
				{
					this.OntakoffChanging(value);
					this.SendPropertyChanging();
					this._takoff = value;
					this.SendPropertyChanged("takoff");
					this.OntakoffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_landing", DbType="NVarChar(50)")]
		public string landing
		{
			get
			{
				return this._landing;
			}
			set
			{
				if ((this._landing != value))
				{
					this.OnlandingChanging(value);
					this.SendPropertyChanging();
					this._landing = value;
					this.SendPropertyChanged("landing");
					this.OnlandingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reservationdb")]
	public partial class reservationdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _mobile;
		
		private string _passengers;
		
		private string _flight;
		
		private string _route;
		
		private string _seats;
		
		private string _payment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnpassengersChanging(string value);
    partial void OnpassengersChanged();
    partial void OnflightChanging(string value);
    partial void OnflightChanged();
    partial void OnrouteChanging(string value);
    partial void OnrouteChanged();
    partial void OnseatsChanging(string value);
    partial void OnseatsChanged();
    partial void OnpaymentChanging(string value);
    partial void OnpaymentChanged();
    #endregion
		
		public reservationdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(50)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passengers", DbType="NVarChar(50)")]
		public string passengers
		{
			get
			{
				return this._passengers;
			}
			set
			{
				if ((this._passengers != value))
				{
					this.OnpassengersChanging(value);
					this.SendPropertyChanging();
					this._passengers = value;
					this.SendPropertyChanged("passengers");
					this.OnpassengersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight", DbType="NVarChar(50)")]
		public string flight
		{
			get
			{
				return this._flight;
			}
			set
			{
				if ((this._flight != value))
				{
					this.OnflightChanging(value);
					this.SendPropertyChanging();
					this._flight = value;
					this.SendPropertyChanged("flight");
					this.OnflightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_route", DbType="NVarChar(50)")]
		public string route
		{
			get
			{
				return this._route;
			}
			set
			{
				if ((this._route != value))
				{
					this.OnrouteChanging(value);
					this.SendPropertyChanging();
					this._route = value;
					this.SendPropertyChanged("route");
					this.OnrouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seats", DbType="NVarChar(50)")]
		public string seats
		{
			get
			{
				return this._seats;
			}
			set
			{
				if ((this._seats != value))
				{
					this.OnseatsChanging(value);
					this.SendPropertyChanging();
					this._seats = value;
					this.SendPropertyChanged("seats");
					this.OnseatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment", DbType="NVarChar(50)")]
		public string payment
		{
			get
			{
				return this._payment;
			}
			set
			{
				if ((this._payment != value))
				{
					this.OnpaymentChanging(value);
					this.SendPropertyChanging();
					this._payment = value;
					this.SendPropertyChanged("payment");
					this.OnpaymentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.routesdb")]
	public partial class routesdb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _type;
		
		private string _model;
		
		private string _startdest;
		
		private string _enddest;
		
		private string _takeoff;
		
		private string _landing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnstartdestChanging(string value);
    partial void OnstartdestChanged();
    partial void OnenddestChanging(string value);
    partial void OnenddestChanged();
    partial void OntakeoffChanging(string value);
    partial void OntakeoffChanged();
    partial void OnlandingChanging(string value);
    partial void OnlandingChanged();
    #endregion
		
		public routesdb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="NVarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdest", DbType="NVarChar(50)")]
		public string startdest
		{
			get
			{
				return this._startdest;
			}
			set
			{
				if ((this._startdest != value))
				{
					this.OnstartdestChanging(value);
					this.SendPropertyChanging();
					this._startdest = value;
					this.SendPropertyChanged("startdest");
					this.OnstartdestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enddest", DbType="NVarChar(50)")]
		public string enddest
		{
			get
			{
				return this._enddest;
			}
			set
			{
				if ((this._enddest != value))
				{
					this.OnenddestChanging(value);
					this.SendPropertyChanging();
					this._enddest = value;
					this.SendPropertyChanged("enddest");
					this.OnenddestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_takeoff", DbType="NVarChar(50)")]
		public string takeoff
		{
			get
			{
				return this._takeoff;
			}
			set
			{
				if ((this._takeoff != value))
				{
					this.OntakeoffChanging(value);
					this.SendPropertyChanging();
					this._takeoff = value;
					this.SendPropertyChanged("takeoff");
					this.OntakeoffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_landing", DbType="NVarChar(50)")]
		public string landing
		{
			get
			{
				return this._landing;
			}
			set
			{
				if ((this._landing != value))
				{
					this.OnlandingChanging(value);
					this.SendPropertyChanging();
					this._landing = value;
					this.SendPropertyChanged("landing");
					this.OnlandingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
